Publish API docs via CircleCI
erik-whiting/biopython pull request #1
Opened 2021-11-09 22:47 UTC by erik-whiting

- [ ] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [ ] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #...

2021-11-10 10:13 UTC, peterjc commented on .github/deploy_docs.sh
> -# Assumes being called from the Biopython repository's root folder,
I would retain comment lines 8 to 15 about this script being run after sphinx-build

2021-11-10 10:23 UTC, peterjc requested changes
The git commit message needs tweaking (see in-line comment).

A lot of the changes are on the comments / human procedure. Was there a vital change in the script itself as well, or was it most likely I missed a set on the CircleCI side when I tried this before?

2021-11-10 10:23 UTC, peterjc commented on .github/deploy_docs.sh
> +# in the Biopython project seetings. To get this value in a format
Typo: settings

2021-11-10 10:23 UTC, peterjc commented on .gitignore
> +biopython_doc_key*
Should probably add ``biopython_doc_key.pub`` too, but this hardly seem worth doing to me. This should only exist on one developer's machine - and most likely won't even be in this directory (I used to use ``~/.ssh/`` for this).

2021-11-10 10:23 UTC, peterjc commented on .github/deploy_docs.sh
> +    git commit -m "Automated update ${COMMIT_HASH}"
Sadly that will give the most recent git commit on the documentation repository, e.g. the commit comment for https://github.com/erik-whiting/docs/commit/ba92d210963f117487d2088d3dcb619e174701d2 points to https://github.com/erik-whiting/docs/commit/b6d8aef0eaead6759ef239dcb057ebf4ddb117ba

You can probably move the ``COMMIT_HASH=$(git rev-parse HEAD)`` line up the script before leaving the clone of the source code repository?

2021-11-10 10:23 UTC, peterjc commented on .gitignore
> +biopython_doc_key*
i.e. Ignore both key files, or don't add either of them.

2021-11-10 10:24 UTC, peterjc commented
I see you got it to work on https://github.com/erik-whiting/docs which is great.

Note you will need to agree to the licensing before we merge this.

2021-11-10 10:26 UTC, peterjc commented
Sorry, I missed this was a PR into your own repository - the one I should be focussed on is https://github.com/biopython/biopython/pull/3787

2021-11-12 19:11 UTC, erik-whiting commented
Merged in the main project

2021-11-12 19:11 UTC, closed without merging